* INTRODUCTION
* VERSION
  See http://tools.android.com/download/studio/canary/1-2-2
  #+NAME: VERSION
  #+BEGIN_SRC sh
    VERSION="1.2.2.0"
    BUILD_NO="141.1980579"
    DOWNLOAD_DIR="$HOME/Downloads"
  #+END_SRC
* Step by Step
  1. [ ] Install Java
     #+BEGIN_SRC sh
       sudo pacman --sync jdk8-openjdk
       #  wget https://aur.archlinux.org/packages/jd/jdk/jdk.tar.gz
     #+END_SRC
  2. [ ] Read http://developer.android.com
  3. [ ] Select [[http://developer.android.com/sdk/index.html][Download Android Studio and SDK Tools]]
  4. [ ] Download Android Studio for Linux with wget
     #+BEGIN_SRC sh :noweb yes :tangle bin/download-android-studio.sh :shebang #!/bin/bash
       set -o nounset
       set -o errexit
       set -o verbose

       <<VERSION>>
 
      ZIP_FILE="android-studio-ide-${BUILD_NO}-linux.zip"
       DOWNLOAD_URL="https://dl.google.com/android/studio/ide-zips/${VERSION}/${ZIP_FILE}"

       mkdir --parent ${DOWNLOAD_DIR}
       cd ${DOWNLOAD_DIR}
     
       echo "Downloading ${DOWNLOAD_URL}"
       wget ${DOWNLOAD_URL}
     #+END_SRC
  5. [ ] Unpack Android Studio for Linux
     #+BEGIN_SRC sh :noweb yes :tangle bin/unpack-android-studio.sh :shebang #!/bin/bash
       set -o nounset
       set -o errexit
       set -o verbose

       <<VERSION>>

       ZIP_FILE="$DOWNLOAD_DIR/android-studio-ide-$BUILD_NO-linux.zip"
       DEVELOPMENT_DIR=~/Development
       mkdir --parent ~/Development
       unzip $ZIP_FILE -d ~/Development

       #        To set up Android Studio on Linux:

       # Unpack the downloaded Tar file, android-studio-ide-<version>-linux.zip, into an appropriate location for your applications.
       # To launch Android Studio, navigate to the android-studio/bin/ directory in a terminal and execute studio.sh.
       # You may want to add android-studio/bin/ to your PATH environmental variable so that you can start Android Studio from any directory.
       # Follow the links to install the SDK outside of the Android Studio directories.
     #+END_SRC
  6. [ ] Run studio.sh
  7. [ ] http://developer.android.com/sdk/installing/index.html?pkg=studio
  8. [ ] add android-studio/bin/ to your PATH environmental variable
     
* Author Notes <troydwill@gmail.com>
** 2015-05-28
   
** 2015-05-17
*** Android Readout

Downloading android-sdk_r22.6.2-linux.tgz from https://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
Unpacking android-sdk_r22.6.2-linux.tgz
/usr/bin/tar xzvfC /tmp/AndroidStudio0FirstRun/android-sdk_r22.6.2-linux.tgz /tmp/AndroidStudio0FirstRun/android-sdk_r22.6.2-linux.tgz-unpacked
Refresh Sources:
  Fetched Add-ons List successfully
  Refresh Sources

Installing Archives:
  Preparing to install archives
  Installing Android SDK Platform-tools, revision 22
  Stopping ADB server failed (code -1).
    Installed Android SDK Platform-tools, revision 22
  Installing Android SDK Build-tools, revision 22.0.1
    Installed Android SDK Build-tools, revision 22.0.1
  Installing SDK Platform Android 5.1.1, API 22, revision 2
    Installed SDK Platform Android 5.1.1, API 22, revision 2
  Installing Sources for Android SDK, API 22, revision 1
    Installed Sources for Android SDK, API 22, revision 1
  Installing Android Support Repository, revision 14
    Installed Android Support Repository, revision 14
  Installing Google Repository, revision 17
    Installed Google Repository, revision 17
  Installing Android SDK Tools, revision 24.2
    Installed Android SDK Tools, revision 24.2
  Installing Google APIs, Android API 22, revision 1
    Installed Google APIs, Android API 22, revision 1
  Installing Google APIs Intel x86 Atom System Image, Google Inc. API 22, revision 1
    Installed Google APIs Intel x86 Atom System Image, Google Inc. API 22, revision 1
    Updated ADB to support the USB devices declared in the SDK add-ons.
    Stopping ADB server succeeded.
    Starting ADB server succeeded.
  Done. 9 packages installed.
Android SDK is up to date.
Creating Android virtual device
Android virtual device Nexus_5_API_22_x86 was successfully created
*** Table   
   | AndroidStudio0FirstRun/android-sdk_r22.6.2-linux.tgz |
   | ./temp/platform-tools_r22-linux.zip                  |
   | ./temp/build-tools_r22.0.1-linux.zip                 |
   | ./temp/sources-22_r01.zip                            |
   | ./temp/android-22_r02.zip                            |
   | ./temp/android_m2repository_r14.zip                  |
   | ./temp/google_m2repository_r17.zip                   |
   | ./temp/tools_r24.2-linux.zip                         |
   | ./temp/sysimg_x86-22_r01.zip                         |
   |                                                      |

   #+BEGIN_SRC sh :tangle /tmp/rsync01.sh
     mkdir --parent ~/Development/RSYNC
     while [ 1 ]; do
         rsync -av --progress /tmp/AndroidStudio0FirstRun ~/Development/RSYNC/
         sleep 1
     done
   #+END_SRC
   #+BEGIN_SRC sh :tangle /tmp/rsync02.sh
     mkdir --parent ~/Development/RSYNC
     while [ 1 ]; do
         rsync -av --progress ~/Android/Sdk/temp ~/Development/RSYNC/
         sleep 1
     done
   #+END_SRC
** 2015-05-14
*** List of packages
    1. Google Inc. x86 System Image, Android 22
    2. Google Repository, rev 17
    3. Android Support Repository, rev 14
    4. Android SDK Build-Tools 22.0.1
    5. Google APIs, Android 22
    6. Android SDK Platform-Tools 22
    7. Android SDK Tools 24.2
*** Downloaded by Android Studio
    1. Android SDK Tools, revision 24.2 to /home/troy/Android/Sdk/temp/tools_r24.2-linux.zip
    2. Android SDK Platform-tools, revision 22
    3. Android SDK Build-tools, revision 22.0.1
    4. Android Support Repository, revision 14
    5. Installing Google Repository, revision 17
*** Errors
    1. Skipping 'Google APIs, Android API 22, revision 1'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed
    2. The following SDK components were not installed: sys-img-addon-google-apis-google-22 and addon-google_apis-google-22
*** Pass 2
    1. Google Inc. x86 System Image, Android 22
    2. Google APIs, Android 22
*** Clean Install
    #+BEGIN_SRC sh :tangle /tmp/clean-android.sh :shebang #!/usr/bin/bash
      set -o verbose
      set -o nounset
      cd ~
      RM="rm -rvf"
      ${RM} -rf ~/.android
      ${RM} -rf ~/Android
      ${RM} -rf ~/.AndroidStudio1.2
      ${RM} -rf ~/AndroidStudioProjects
      ${RM} -rf ~/Development/android-studio
    #+END_SRC
** Check http://tools.android.com/download/studio/stable for version
** Android Studio IDE download package
|     Date | file                                     | size | md5sum                           |
|----------+------------------------------------------+------+----------------------------------|
| 14-12-11 | android-studio-ide-135.1629389-linux.zip | 233M | a4b852b1e1bb530010275e702cf4661c |
|          |                                          |      |                                  |
   

