* Installing Shiloh System step by step
1. [ ] Connect to the internet
2. (Optional) Read the wiki.archlinux.org [[https://wiki.archlinux.org/index.php/Beginners'_Guide][Beginner's Guide]]
3. [ ] Prepare the target media with parted and GPT
   1. (Optional) Run lsblk to determine drive
      #+BEGIN_SRC sh
        lsblk
      #+END_SRC
   2. (Optional) Zero drive
      #+BEGIN_SRC sh :tangle bin/partition/zero-the-drive.sh :shebang #!/usr/bin/bash
	set -o errexit
        set -o nounset
        set -o verbose

	DEVICE="/dev/sda" # find DEVICE with /usr/bin/lsblk and edit this line
	BS="1M"
	COUNT=4
        # exit
	dd if=${DEVICE} of=SECTOR bs=$BS count=$COUNT
	dd if=/dev/zero of=${DEVICE} bs=$BS count=$COUNT

        dd if=${DEVICE} bs=1M count=$COUNT | hexdump -C


        # Create a GUID partition table with parted
        parted --script ${DEVICE} mklabel gpt
        dd if=${DEVICE} bs=1M count=$COUNT | hexdump -C


        # Create an EFI partition with parted
        parted --script ${DEVICE} mkpart ESP fat32 1MiB 513MiB set 1 boot on

        # Format the boot partition 
        mkfs.vfat -F32 ${DEVICE}1

        # Create a root partition with parted
        parted --script ${DEVICE} mkpart primary ext4 513MiB 50%

        # Format the root partition
	LABEL="20150718" #change this!
	mkfs.ext4 -v -L $LABEL ${DEVICE}2
        
      #+END_SRC
   3. [ ] 
      #+BEGIN_SRC sh :tangle bin/partition/format-the-root-partion.sh :shebang #!/bin/bash
	set -o nounset
	set -o errexit
	LABEL="20150712" #change this!
	DEVICE="/dev/sdb2" #change this!
        exit
	mkfs.ext4 -v -L $LABEL $DEVICE
      #+END_SRC
4. [ ] Mount the partitions
   1. [ ] Mount the root partition
      #+BEGIN_SRC sh
        sudo mount /dev/sdb2 /mnt
      #+END_SRC
   2. [ ] Mount the boot partition
      #+BEGIN_SRC sh
        mkdir -p /mnt/boot
        mount /dev/sdb1 /mnt/boot
      #+END_SRC
5. [ ] Install the system
   1. [ ] Install arch-install-scripts
      #+begin_src sh
	sudo pacman --sync arch-install-scripts
      #+end_src
   2. (Optional) Copy xz files or link symbolically to host pkg directory
      #+begin_src sh :tangle bin/optional/copy-existing-pkg-cache :shebang #!/bin/bash
	set -o nounset
	set -o errexit
	sudo mkdir --verbose --parent /mnt/var/cache/pacman/pkg
	sudo rsync --archive --progress --verbose /var/cache/pacman/pkg/* /mnt/var/cache/pacman/pkg
      #+end_src
   3. [ ] Install packages with pacstap
      Before installing, you may want to edit /etc/pacman.d/mirrorlist such that your
      preferred mirror is first. This copy of the mirrorlist will be installed on your
      new system by pacstrap} as well, so it's worth getting it right.
      
      Using the pacstrap script we install the base system. The 'base-devel' package group
      should also be installed if you plan on compiling software from the [[AUR]] or using [[ABS]].
      
      Other packages can be installed by appending their names to the above command (space
      seperated), including the bootloader if you want.
      
      #+BEGIN_SRC sh :tangle bin/pacstrap.sh :shebang #!/bin/bash
	set -o errexit
	set -o nounset
	# July 12, 2015
	# INSTALL="grub os-prober arch-install-scripts parted linux-lts"
	INSTALL="grub os-prober arch-install-scripts parted"
	DEVEL="base-devel git stow cmake"
	SYSTEM="ntp openssh rsync screen sudo wget pkgfile abs"
	SYSTEM="openssh rsync screen sudo wget pkgfile abs"
	EMACS="emacs"
	TEX="texlive-core texlive-latexextra"
	WIRELESS="wireless_tools wpa_supplicant"
	XORG="xorg-server xorg-xinit xf86-video-intel xf86-input-synaptics"
	XORG_FONTS="ttf-dejavu ttf-hannom"
	WEB="chromium firefox"
	KDE="konsole gwenview kdebase-konqueror kstars kdebase-workspace"
	# LXQT="openbox"
	AUDIO="alsa-utils pulseaudio-alsa pavucontrol"
	VIDEO="flashplugin youtube-dl smplayer"
	VIDEO="youtube-dl smplayer"
	# pacstrap /mnt base $INSTALL $DEVEL $SYSTEM $EMACS $WIRELESS $XORG $WEB $KDE $LXQT $AUDIO $VIDEO $XORG_FONTS
	pacstrap /mnt base $INSTALL $DEVEL $SYSTEM $EMACS $WIRELESS $XORG $WEB $KDE $AUDIO $VIDEO $XORG_FONTS
      #+END_SRC  
6. [ ] Configure the system
   1. [ ] Generate an /etc/fstab file
      #+BEGIN_SRC sh :tangle bin/configure/fstab.sh :shebang #!/bin/bash
        set -o verbose
        # if you prefer to use UUIDs or labels,
        # add the -U or -L option
        sudo genfstab -pU /mnt >> /mnt/etc/fstab
      #+END_SRC
   2. [ ] copy shiloh-system to new root directory
      #+BEGIN_SRC sh
          sudo cp --archive shiloh-system/ /mnt/root
      #+END_SRC
   3. [ ] chroot into the newly installed system
      #+BEGIN_SRC sh
        sudo arch-chroot /mnt
      #+END_SRC
   4. [ ] Write your hostname to /etc/hostname.
      #+BEGIN_SRC sh :tangle bin/configure/hostname.sh :shebang #!/bin/bash
        set -o nounset
        HOSTNAME="kangaroo" # change this!
        echo $HOSTNAME > /etc/hostname
      #+END_SRC
   5. [ ] Symlink /etc/localtime to /usr/share/zoneinfo/Zone/SubZone.
      - Replace Zone and Subzone to your liking. For Los_Angeles:
        #+BEGIN_SRC sh :tangle bin/configure/timezone.sh :shebang #!/bin/bash
          set -o verbose

          ln -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
          ls -l /etc/localtime
        #+END_SRC   
   6. [ ] Set [[https://wiki.archlinux.org/index.php/Locale#Setting_system-wide_locale][locale]] preferences in /etc/locale.conf
      #+BEGIN_SRC sh :tangle bin/configure/locale.sh :shebang #!/bin/bash
        set -o verbose

        cat /etc/locale.conf
        echo 'LANG="en_US.UTF-8"' > /etc/locale.conf
        cat /etc/locale.conf
      #+END_SRC
   7. [ ] Uncomment en_US.UTF-8 in /etc/locale.gen
      #+begin_src perl :tangle bin/configure/locale-gen.pl :shebang #!/usr/bin/env perl
        use warnings;
        use strict;
        my $regexp = '^#en_US.UTF-8 UTF-8';
        my $replacement = 'en_US.UTF-8 UTF-8';
        open(my $oldlocale, "<", "/etc/locale.gen")      # open for update
            or die "Can't open '/etc/locale.gen' for reading: $!";
        open(my $newlocale, ">", "/etc/locale.gen.tmp")
            or die "Can't open '/tmp/locale.gen' for writing: $!";
        while (<$oldlocale>) {
            s/$regexp/$replacement/;
            print $newlocale $_ or die "can't write $newlocale: $!";;
        }
        
        close($oldlocale)            or die "can't close $oldlocale: $!";
        close($newlocale)            or die "can't close $newlocale: $!";
        rename("/etc/locale.gen", "/etc/locale.gen.orig")   or die "can't rename /etc/locale.gen /etc/locale.gen.orig: $!";
        rename("/etc/locale.gen.tmp", "/etc/locale.gen") or die "can't rename /etc/locale.gen.tmp /etc/locale.gen: $!";
      #+end_src
   8. [ ] locale-gen
       #+BEGIN_SRC sh
         locale-gen
       #+END_SRC
   9. [ ] Add [[https://wiki.archlinux.org/index.php/KEYMAP][console keymap and font]] preferences in /etc/vconsole.conf
      #+BEGIN_SRC sh :tangle bin/configure/vconsole.sh :shebang #!/bin/bash
        echo KEYMAP=us > /etc/vconsole.conf
      #+END_SRC
   10. [ ] Configure /etc/mkinitcpio.conf as needed (see [[mkinitcpio]]) and create an initial RAM disk
       #+BEGIN_SRC sh :tangle bin/configure/mkinitcpio.sh :shebang #!/bin/bash
         set -o verbose

         mkinitcpio -p linux
       #+END_SRC
7. SKIP TO NEXT SECTION Configure the bootloader: refer back to the appropriate article from the bootloader installation section.
   1. [ ] pacman --sync grub efibootmgr
   2. (Optional) READ https://wiki.archlinux.org/index.php/GRUB2
   3. (Optional) Install osprober if Windows dual boot
      #+begin_src sh
	pacman --sync os-prober
      #+end_src
   4. DELETE run grub-install to cp grub boot files and optionally install to 440-byte MBR boot code region
      #+BEGIN_SRC sh :tangle bin/configure/grub-install.sh :shebang #!/bin/bash
	DEVICE=/dev/sdX #change this as desired!
        exit
	modprobe dm-mod
	sleep 1
	grub-install --target=i386-pc --recheck --debug $DEVICE
	cp --verbose /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
      #+END_SRC
   5. grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=grub --recheck
   6. grub-mkconfig -o /boot/grub/grub.cfg
   7. DELETE Generate GRUB2 BIOS Config file
      #+BEGIN_SRC sh :tangle bin/configure/grub-config.sh :shebang #!/bin/bash
        set -o verbose

	grub-mkconfig -o /boot/grub/grub.cfg
      #+END_SRC
8. [ ] https://wiki.archlinux.org/index.php/Systemd-boot
   1. [ ] Install
      #+BEGIN_SRC sh
        bootctl --path=/boot install
      #+END_SRC
   2. [ ] file:/mnt/boot/loader/loader.conf
      #+BEGIN_SRC sh
        #timeout 3
        #default e7a68106fb4a4eb3b9608aebd437de41-*
        default arch
        timeout 10
      #+END_SRC
   3. [ ] sudo blkid -s PARTUUID -o value /dev/sdb2
      #+BEGIN_SRC sh
        9930d7be-0f3e-4ddb-9b4d-422e2e94f407
      #+END_SRC
   4. [ ] file:/mnt/boot/loader/entries/arch.conf
      #+BEGIN_SRC sh
        title          Shiloh GNU/Linux
        linux          /vmlinuz-linux
        initrd         /initramfs-linux.img
        options        root=PARTUUID=9930d7be-0f3e-4ddb-9b4d-422e2e94f407 rw
      #+END_SRC
9. [ ] Set a root password with passwd.
10. [ ] Add a user
    #+BEGIN_SRC sh :tangle bin/configure/adduser.sh :shebang #!/bin/bash
      useradd -m -g users -s /bin/bash troy
      passwd troy
    #+END_SRC   
11. [ ] Setup sudo
    #+BEGIN_SRC perl :tangle bin/configure/sudo.pl :shebang #!/usr/bin/env perl
      use warnings;
      use strict;
      
      print "User? ";
      chomp(my $user = <STDIN>);
      
      open ( my $out, '>>', '/etc/sudoers' );
      print $out <<"END";
      ### Following lines added by sudo.pl
      # Defaults specification
      Defaults:troy timestamp_timeout=-1
      Defaults !tty_tickets
      # User privilege specification
      root    ALL=(ALL) ALL
      $user   ALL=(ALL) ALL
      END
      
      sub run_command {
          my $command = shift;
          print "=> $command\n";
          system $command;
      }
    #+END_SRC
12. [ ] Unmount and reboot
    If you are still in the chroot environment type exit or press Ctrl+D in order to exit.
    Earlier we mounted the partitions under /mnt. In this step we will unmount them:
    #+BEGIN_SRC sh
      umount /mnt/{boot,home,}
    #+END_SRC
    Now reboot and then login into the new system with the root account.
** TODO Configure pacman
Edit /etc/pacman.conf and configure pacman's options, also enabling the repositories you need.

See [[Pacman]] and [[Official Repositories]] for details.

== Update the system ==
At this point you should update your system.

See [[Pacman#Upgrading packages|Upgrading packages]] for instructions.

== Add a user ==
Finally, add a normal user as described in [[Users and Groups#User management|User management]].

Your new Arch Linux base system is now a functional GNU/Linux environment: you can proceed to [[Beginners' Guide/Extra]] for customization suggestions.
* Disk partioning documentation
* Bootloader documentation
* Networking
** wpa
   #+BEGIN_SRC sh :tangle NETWORKING/generate-wpa-config.sh :shebang #!/bin/bash
     set -o errexit
     set -o nounset
     SSID="my_ssid"
     PASSPHRASE="my_passphrase"

     wpa_passphrase $SSID $PASSPHRASE >> wpa_supplicant.conf
   #+END_SRC
   #+BEGIN_SRC sh :tangle NETWORKING/wpa_supplicant.sh :shebang #!/bin/bash 
     set -o nounset
     INTERFACE='wlp1s0'
     sudo wpa_supplicant -B -i${INTERFACE} -c ./wpa_supplicant.conf 
     sudo dhcpcd ${INTERFACE}
   #+END_SRC
