#!/usr/bin/env perl
use warnings;
use strict;

&run_command ('pacman --sync ttf-dejavu ttf-bitstream-vera ttf-hannom');

sub run_command {
    my $command = shift;
    print "=> $command\n";
    system $command;
}

